version: "3"

vars:
  BINARY: simple-aws-sso
  BIN_DIR: bin

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BIN_DIR}}/{{.BINARY}}"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.BINARY}} .

  run:
    desc: Run the application
    deps:
      - build
    cmds:
      - ./{{.BIN_DIR}}/{{.BINARY}} {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf dist
      - rm -f coverage.out coverage.html

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy

  release:snapshot:
    desc: Build release locally (no publish)
    cmds:
      - goreleaser release --snapshot --clean

  release:check:
    desc: Validate goreleaser config
    cmds:
      - goreleaser check

  version:
    desc: Show current version
    cmds:
      - |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Current version: $TAG"

  release:
    desc: "Create a release: task release -- [patch|minor|major]"
    cmds:
      - |
        BUMP_TYPE="{{.CLI_ARGS}}"
        if [ -z "$BUMP_TYPE" ]; then
          echo "Usage: task release -- [patch|minor|major]"
          exit 1
        fi

        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        MAJOR=$(echo $TAG | sed 's/v//' | cut -d. -f1)
        MINOR=$(echo $TAG | sed 's/v//' | cut -d. -f2)
        PATCH=$(echo $TAG | sed 's/v//' | cut -d. -f3)

        case "$BUMP_TYPE" in
          patch)
            NEW="v${MAJOR}.${MINOR}.$((PATCH + 1))"
            ;;
          minor)
            NEW="v${MAJOR}.$((MINOR + 1)).0"
            ;;
          major)
            NEW="v$((MAJOR + 1)).0.0"
            ;;
          *)
            echo "Invalid bump type: $BUMP_TYPE"
            echo "Usage: task release -- [patch|minor|major]"
            exit 1
            ;;
        esac

        echo "Bumping $TAG → $NEW"
        git tag $NEW
        git push origin $NEW
